"""
demo_presets.py
================
Small, deterministic demo outputs for client-facing demos.

For 1–5 qubits we return a pre-authored Qiskit Metal script (as a string) that
users can copy/download, even if the server is running in schematic mode.

These scripts are intentionally minimal and headless-friendly.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class DemoPreset:
    n: int
    topology: str
    title: str
    code: str


def _read_asset_b64(filename: str) -> str | None:
    from pathlib import Path
    import base64

    path = Path(__file__).resolve().parent / "demo_assets" / filename
    if not path.is_file():
        return None
    return base64.b64encode(path.read_bytes()).decode("utf-8")


def _grid_positions_um(n: int) -> list[tuple[float, float]]:
    # Simple deterministic grid for 1–5 qubits.
    if n <= 1:
        return [(0.0, 0.0)]
    if n == 2:
        return [(0.0, 0.0), (1000.0, 0.0)]
    if n == 3:
        return [(0.0, 0.0), (1000.0, 0.0), (0.0, 1000.0)]
    if n == 4:
        return [(0.0, 0.0), (1000.0, 0.0), (0.0, 1000.0), (1000.0, 1000.0)]
    # n == 5
    return [(0.0, 0.0), (1000.0, 0.0), (0.0, 1000.0), (1000.0, 1000.0), (500.0, 2000.0)]


def _metal_script_for_grid(n: int) -> str:
    positions = _grid_positions_um(n)
    qubit_lines = []
    for i, (x, y) in enumerate(positions):
        qubit_lines.append(
            f"TransmonPocket(design, 'q{i}', options=dict(pos_x='{x}um', pos_y='{y}um', pad_width='400um', pad_height='90um', pad_gap='30um'))"
        )

    return f'''"""
QBETA Demo Preset — Grid {n}Q (Qiskit Metal)
Generated by QBETA backend (demo preset).

Notes:
- This is a COPY/PASTE script for Qiskit Metal 0.7.x.
- Runs headless by default (no GUI).
"""

import os
os.environ.setdefault("QISKIT_METAL_HEADLESS", "1")
os.environ.setdefault("QISKIT_METAL_SUPPRESS_RENAME_WARNING", "1")

from qiskit_metal import designs
from qiskit_metal import Dict
from qiskit_metal.qlibrary.qubits.transmon_pocket import TransmonPocket
from qiskit_metal.qlibrary.terminations.launchpad_wb import LaunchpadWirebond
from qiskit_metal.qlibrary.tlines.meandered import RouteMeander
from qiskit_metal.qlibrary.tlines.straight_path import RouteStraight

# Optional (GDS export, requires gdspy):
# from qiskit_metal.renderers.renderer_gds.gds_renderer import QGDSRenderer

design = designs.DesignPlanar()
design.overwrite_enabled = True

# ---- Qubits ----
{chr(10).join(qubit_lines)}

# ---- Simple per-qubit launchpads (top edge) ----
for i in range({n}):
    LaunchpadWirebond(
        design,
        f"lp_{{i}}",
        options=Dict(pos_x=f"{{i*1.2}}mm", pos_y="4.0mm", orientation="270"),
    )

# ---- Readout resonators (qubit -> launchpad) ----
for i in range({n}):
    RouteMeander(
        design,
        f"ro_{{i}}",
        options=Dict(
            pin_inputs=Dict(
                start_pin=Dict(component=f"q{{i}}", pin="readout"),
                end_pin=Dict(component=f"lp_{{i}}", pin="tie"),
            ),
            meander=Dict(spacing="200um", asymmetry="0um"),
            lead=Dict(start_straight="10um", end_straight="50um"),
            fillet="99.9um",
        ),
    )

# ---- Nearest-neighbour coupling buses (straight) ----
for i in range({max(0, n - 1)}):
    RouteStraight(
        design,
        f"bus_{{i}}",
        options=Dict(
            pin_inputs=Dict(
                start_pin=Dict(component=f"q{{i}}", pin="a"),
                end_pin=Dict(component=f"q{{i+1}}", pin="c"),
            ),
        ),
    )

design.rebuild()
print(f"Built demo preset: {n}Q grid. Components={{len(design.components)}}")

# ---- Optional GDS ----
# gds = QGDSRenderer(design)
# gds.options.path_filename = "./qbeta_demo_chip.gds"
# gds.export_to_gds()
'''


def get_demo_preset(n: int, topology: str) -> DemoPreset | None:
    """Return demo preset for 1–5 qubits. Currently supports grid only."""
    if n < 1 or n > 5:
        return None
    topo = topology if topology in ("grid", "line", "star", "ring") else "grid"
    # For demos we standardize to a clean grid script for now.
    return DemoPreset(
        n=n,
        topology=topo,
        title=f"Demo Preset — {n}Q {topo}",
        code=_metal_script_for_grid(n),
    )


def get_demo_fabricated_image_b64(n: int) -> str | None:
    """Return a pre-rendered Qiskit Metal fabricated PNG for 1–5 qubits."""
    if n < 1 or n > 5:
        return None
    return _read_asset_b64(f"fabricated_{n}q.png")


def get_demo_code(n: int, topology: str = "grid") -> str | None:
    """Return stored Metal script from demo_assets if generated with Metal."""
    from pathlib import Path

    path = Path(__file__).resolve().parent / "demo_assets" / f"qbeta_{n}q.py"
    if path.is_file():
        return path.read_text(encoding="utf-8")
    preset = get_demo_preset(n, topology)
    return preset.code if preset else None


def demo_assets_ready() -> bool:
    """True if all 1–5 Q Metal PNG presets exist."""
    from pathlib import Path

    base = Path(__file__).resolve().parent / "demo_assets"
    return all((base / f"fabricated_{n}q.png").is_file() for n in range(1, 6))


def get_demo_manifest() -> dict | None:
    from pathlib import Path
    import json

    path = Path(__file__).resolve().parent / "demo_assets" / "manifest.json"
    if not path.is_file():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None

